language: go
go_import_path: github.com/kubernetes-sigs/aws-efs-csi-driver

env:
  global:
    - GO111MODULE=on

go:
  - "1.13.4"

before_install:
  - go get github.com/mattn/goveralls

script:
  - make
  - go test -covermode=count -coverprofile=profile.cov $(go list ./pkg/... | grep -v /driver)
    # TODO stop skipping controller tests when controller is implemented
  - go test -covermode=count -coverprofile=profile.cov ./pkg/driver/... -ginkgo.skip='\[Controller.Server\]'
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
